import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '@/components/Header'
import Feed from '@/components/Feed'
import Modal from '@/components/Modal'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-gray-50 h-screen overflow-y-scroll'>
      <Head>
        <title>Havir Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* modal */}
      <Modal />
  
      {/* header */}
      <Header />

      {/* feed */}
      <Feed />

      
    </div>
  )
}
